# Generated by Django 5.2.8 on 2025-11-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bookcar_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/'),
        ),
    ]
