# Generated by Django 5.2.8 on 2025-11-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bookcar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcar',
            name='withDriver',
            field=models.CharField(default='withoutDriver', max_length=50),
        ),
    ]
