# Generated by Django 5.2.8 on 2025-11-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bookcar_withdriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcar',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
