# Generated by Django 5.2.8 on 2025-11-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bookcar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcar',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
