# Generated by Django 5.2.8 on 2025-11-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bookcar_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcar',
            name='payment_mode',
            field=models.CharField(default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='bookcar',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='bookcar',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookcar',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
