# Generated by Django 5.2.8 on 2025-11-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bookcar_payment_mode_bookcar_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcar',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='bookcar',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='bookcar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='bookcar',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cashless', 'Cashless')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookcar',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
